### ISSUE TITLE
the map parameter is ignored when the osm-relation is specified

### ISSUE THREAD

**Issue by milossramek** [enu-sav/freemap-snapshot#1]
If we specify a certain osm-relation, then the (custom) map=11/48.778818/17.889175 parameter is ignored. This means for us that on illustration reopening not the correct zoom and position are displayed but the default one. We would prefer that the 'map' parameter is not ignored if osm-relation is specified.

Example:
https://www.freemap.sk/#map=11/48.778818/17.889175&layers=O&osm-relation=1556716&embed=search

**Comment by zdila** [comment]
`map` parameter is ignored only if you visit such URL directly. Using it with freemap-snapshot works correctly, try for example: `curl --request POST   --url http://localhost:8080/   --header 'content-type: application/json'   --header 'user-agent: vscode-restclient'   --data '{"url": "https://www.freemap.sk/#map=10/48.738078/20.722726&layers=O&osm-relation=2382083","viewport": {"width": 800,"height": 600,"deviceScaleFactor": 2},"searchResultStyle": {"color": "purple"}}' | display`
